---
  - name: Checkout dehydrated
    git:
      repo: "https://github.com/lukas2511/dehydrated.git"
      dest: "/opt/dehydrated"
      version: master
      force: yes

  - name: create /etc/letsencrypt hierarchy
    file: dest=/etc/{{ item }}
          owner=root group=ssl-cert
          state=directory mode=0750
    with_items:
      - "letsencrypt"
      - "letsencrypt/live"
      - "letsencrypt/live/{{ domain }}"
      - "letsencrypt/renewal-hooks/"
      - "letsencrypt/renewal-hooks/post"

  - name: generate dehydrated folders
    file: dest=/etc/{{ item }}
          owner=root group=root
          state=directory
    with_items:
      - "dehydrated"
      - "dehydrated/accounts"

  - name: generate dehydrated hook.sh
    copy: dest=/etc/dehydrated/hook.sh
          src=dehydrated/hook.sh
          owner=root group=root mode=0775

  - name: generate dehydrated dns-01 private & key
    copy: dest=/etc/dehydrated/dns-01-key.{{ item }}
          content={{ lookup('keepass', 'ansible/ssl/dns-01/'+ansible_fqdn+'.attr_'+item) }}
          mode=0640 owner=root group=root
    with_items:
      - key
      - private


  - name: generate dehydrated config
    copy: dest=/etc/dehydrated/config
          src=dehydrated/config
          owner=root group=root mode=0664

  - name: generate dehydrated account directory
    file: dest=/etc/dehydrated/accounts/{{ lookup('keepass', 'ansible/ssl/letsencrypt-account.username') }}
          state=directory
          owner=root group=root mode=0750

  - name: generate dehydrated account_key.pem
    copy: dest=/etc/dehydrated/accounts/{{ lookup('keepass', 'ansible/ssl/letsencrypt-account.username') }}/account_key.pem
          content={{ lookup('keepass', 'ansible/ssl/letsencrypt-account.attr_account_key') }}
          owner=root group=root mode=0640

  - name: generate dehydrated registration_info.json
    copy: dest=/etc/dehydrated/accounts/{{ lookup('keepass', 'ansible/ssl/letsencrypt-account.username') }}/registration_info.json
          content={{ lookup('keepass', 'ansible/ssl/letsencrypt-account.attr_registration_info') }}
          owner=root group=root mode=0640

  - name: ensure domain {{ domain }} is in domains.txt
    lineinfile: path=/etc/dehydrated/domains.txt
                state=present
                regexp='{{ domain }}'
                line='{{ domain }}'
                create=yes owner=root group=root mode=0664

  - name: generate or renew certificate (takes up to 5 seconds)
    shell: "/opt/dehydrated/dehydrated --cron"

  - name: generate dehydrated systemd timer unit
    copy: dest=/etc/systemd/system/dehydrated.timer
          src=dehydrated/dehydrated.timer
          owner=root group=root mode=0664

  - name: generate dehydrated systemd service unit
    copy: dest=/etc/systemd/system/dehydrated.service
          src=dehydrated/dehydrated.service
          owner=root group=root mode=0664

  - name: reload systemd daemon
    command: systemctl daemon-reload
    changed_when: false

  - name: disable certbot systemd timer
    service: name=certbot.timer
             enabled=no
             state=stopped
    ignore_errors: yes

  - name: enable dehydrated systemd timer
    service: name=dehydrated.timer
             enabled=yes
             state=started
