---
    - name: create /etc/letsencrypt hierarchy
      file: "dest=/etc/{{ item }}
             owner=root group=ssl-cert
             state=directory mode=0750"
      with_items:
        - "letsencrypt"
        - "letsencrypt/live"
        - "letsencrypt/live/{{ domain }}"
        - "letsencrypt/renewal-hooks/"
        - "letsencrypt/renewal-hooks/post"

    - name: copy over pregenerated certificate data
      copy: "dest=/etc/letsencrypt/live/{{ domain }}/{{ item }}.pem
             content={{ lookup('keepass', 'ansible/ssl/certs/'+letsencrypt_fake+'.attr_'+item) }}
             mode=0640 owner=root group=ssl-cert"
      with_items:
        - fullchain
        - chain
        - cert
        - privkey

  # Cron jobs to update letsencrypt certs
    - name: disable letsencrypt update cron job
      cron: name="update_{{ domain }}" user=letsencrypt state=absent

    - name: disable certbot systemd timer
      service: name=certbot.timer
               enabled=no
               state=stopped
      ignore_errors: yes

    - name: disable dehydrated systemd timer
      service: name=dehydrated.timer
               enabled=no
               state=stopped
      ignore_errors: yes
