---
- group: name="mirrorbits" state=present

- user: state=present
        name="mirrorbits"
        groups="mirrorbits"
        shell="/bin/false"

- file: path=/srv/mirrorbits state=directory
        mode=0755 owner=root group=root

- file: path=/srv/mirrorbits/logs state=directory
        mode=0755 owner=mirrorbits group=root

- git:
    repo: https://github.com/voc/mirrorbits
    dest: /srv/mirrorbits/mirrorbits

- make:
    chdir: /srv/mirrorbits/mirrorbits
    target: install

- template: src=mirrorbits.service
            dest=/etc/systemd/system/mirrorbits.service
            mode=0644 owner=root group=root

- template: src=mirrorbits.conf
            dest=/etc/mirrorbits.conf
            mode=0640 owner=mirrorbits group=root

- copy: src=mirrorbits/templates
        dest=/srv/mirrorbits/
        owner=mirrorbits group=root

- systemd: state=started enabled=yes name=mirrorbits.service
- systemd: state=started enabled=yes name=redis.service
