---
  - name: install default packages
    apt:
      state: latest
      name:
        - build-essential
        - pkg-config
        - zlib1g-dev
        - libgeoip-dev
        - libprotoc-dev
        - unattended-upgrades
        - rsync

  - apt_repository:
      repo: deb http://deb.debian.org/debian buster-backports main
      state: present

  - name: install default packages
    apt: name="{{ item }}" state=latest default_release=buster-backports
    loop:
      - redis-server
