---
  - name: install default packages
    apt:
      state: latest
      name:
        - build-essential
        - pkg-config
        - zlib1g-dev
        - libgeoip-dev
        - libprotoc-dev
        - unattended-upgrades

  - name: install default packages
    apt: name="{{ item }}" state=latest default_release=buster-backports
    loop:
      - redis-server
