---
- file: path=/srv/www/ state=directory
        owner=www-data group=www-data

- git: repo=https://github.com/voc/voctoweb-static
       dest=/srv/www/
       version=master

- group: name="uploaders" state=present
- group: name="cdn-app" state=present

- user: state=present
        name="cdn-app"
        groups="cdn-app,uploaders"
        shell="/usr/bin/rssh"

- git: repo=https://github.com/voc/voctoweb-media
       dest=/srv/www/media.ccc.de/media
       version=master

- file: dest=/srv/www/media.ccc.de/media state=directory recurse=yes
        owner=cdn-app group=cdn-app
