---
  - name: create directories
    file: dest={{ item }} state=directory
          owner=root group=root
    with_items:
      - /opt/transcoder/scripts/
  
  - name: find old systemd files
    find:
      paths: /etc/systemd/system
      recurse: no
      patterns: "^transcode_[^@]*.(target|service|wants)$"
      use_regex: yes
      file_type: any
    register: old_systemd_transcoding_files

  - name: delete old systemd files
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ old_systemd_transcoding_files.files }}"
      
  - name: create h264 transcode-script
    template: dest=/opt/transcoder/scripts/h264.sh
              src=transcoder/h264.sh.j2
              owner=root group=root mode=0755

  - name: create vpx transcode-script
    template: dest=/opt/transcoder/scripts/vpx.sh
              src=transcoder/vpx.sh.j2
              owner=root group=root mode=0755

  - name: create audio transcode-script
    template: dest=/opt/transcoder/scripts/audio.sh
              src=transcoder/audio.sh.j2
              owner=root group=root mode=0755

  - name: create transcode systemd-units
    template: src=systemd-units/transcode.service.j2
              dest="/etc/systemd/system/transcode_{{ item }}@.service"
              mode=0644 owner=root group=root
    with_items:
      - "h264"
      - "vpx"
      - "audio"

  - name: create transcode systemd-target
    template: 
      src: systemd-units/transcode.target.j2
      dest: "/etc/systemd/system/transcode@.target"
      mode: 0644
      owner: root
      group: root

  - name: enable systemd-units
    systemd:
      name: "transcode_{{ item.1 }}@{{ item.0 }}.service"
      enabled: yes
      daemon_reload: yes
    with_nested:
      - "{{ transcoder_streams }}"
      - ["h264", "vpx", "audio"]

  - name: enable and start transcode systemd-target
    systemd: 
      name: "transcode_{{ item }}.target"
      enabled: yes
      started: yes
    with_items:
      - "{{ transcoder_streams_enabled }}"

