---
  - name: create directories
    file: dest={{ item }} state=directory
          owner=root group=root
    with_items:
      - /opt/transcoder/scripts/


  - name: create lounge transcode-script
    template: dest=/opt/transcoder/scripts/lounge.sh
              src=transcoder/lounge.sh.j2
              owner=root group=root mode=0755

  - name: create lounge systemd-units
    template: src=systemd-units/lounge.service.j2
              dest="/etc/systemd/system/transcode_lounge@.service"
              mode=0644 owner=root group=root

  - name: enable & start lounge systemd-units
    systemd: 
      name: transcode_lounge@{{ item }}.service
      enabled: yes
      state: restarted
      daemon_reload: yes
    with_items: "{{ transcoder_lounges }}"
