---
  - name: install system packages for tally pis
    apt: name={{item}} state=latest update_cache=yes
    with_items:
      - python3
      - python3-pip
  - name: install python packages for voctolight
    pip:
      name: RPi.GPIO
      executable: pip3