---
  - name: deploy raidstatus script on system with HW raid
    copy: src=raidstatus
          dest=/usr/local/sbin/raidstatus
          owner=root group=root mode=0750
    when: ansible_hostname is match('dellinger|storage|aws|berlin-ak|mebibyte')

  - name: create check_system script
    template: src="monitoring/check_system.sh.j2"
              dest="/usr/local/sbin/check_system.sh"
              mode=0750 owner=root group=root
    tags:
      - check_recording
      - check_system
      - encodermode
      - voctomix

  - cron: name="check system and send mqtt message"
          minute="*/1" hour="*" month="*" day="*"
          job="nice -n 19 /usr/local/sbin/check_system.sh >/dev/null"

  - name: deploy systemd unit for shutdown hook
    copy: src=send-mqtt-shutdown.service
          dest=/etc/systemd/system/send-mqtt-shutdown.service
          owner=root group=root mode=0640

  - name: reload systemd daemon
    command: systemctl daemon-reload
    changed_when: false

  - name: enable & start shutdown hook
    service: name=send-mqtt-shutdown
             enabled=yes
             state=started
