---
  - name: make resolv.conf writable
    file:
      path: /etc/resolv.conf
      attributes: -i
    changed_when: false

  - name: configure resolv.conf
    template: dest=/etc/resolv.conf
              src=resolv.conf.j2
              owner=root group=root mode=0644
