---
  - name: reload haproxy
    service: name=haproxy state=reloaded

  - name: restart nginx
    service: name=nginx state=restarted

  - name: reload nginx
    service: name=nginx state=reloaded

  - name: reload php7.3-fpm
    service: name=php7.3-fpm state=reloaded

  - name: run startcom ocsp scripts
    shell: "/usr/local/bin/{{ item }} /usr/local/bin/{{ item }} 1>/dev/null"
    become: yes
    become_user: ocsp-updater
    notify:
      - reload haproxy
    with_items:
      - update_cdn_c3voc_de_ocsp_stapling.sh
      - update_streaming_media_ccc_de_ocsp_stapling.sh

  - include: ../../../handlers/systemd.yml
  - include: ../../../handlers/rc_local.yml
  - include: ../../../handlers/sysctl.yml
  - include: ../../../roles/letsencrypt/handlers/main.yml domain={{ ansible_fqdn }}
