# Do not set this db to the same as development or production.
test:
  adapter: sqlite3
  database: db/test.sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  pool: 16
  host: {{ pg_host }}
  database: {{ pg_db }}
  encoding: utf8
  username: {{ pg_user }}
  password: {{ pg_password }}
