---
- name: Add rails user
  user:
    name: media
    shell: /bin/bash
    home: /srv/media
    state: present

- import_tasks: packages.yml
  tags: media-app

- copy: src=goaccess.sh
        dest=/usr/local/bin
        owner=root group=root mode=0755

- template: src=postfix.conf
            dest=/etc/postfix/main.cf
            mode=0644 owner=root group=root

- import_tasks: rails-app.yml
  tags: media-app

# TODO only run on one puma node
- import_tasks: cron.yml
  tags:
    - media-app
    - cron

- copy: src=redis.conf
        dest=/etc/redis/redis.conf
        owner=root group=root mode=0640

- import_tasks: nginx.yml
  tags:
    - nginx

- debug:
    msg:
      - "Manual steps:"
      - ""
      - "create database, import data, etc.:"
      - "   sudo -u postgres pg_dump -F c -b -v -f file media-site"
      - "   sudo -u postgres createdb media-site"
      - "   sudo -u postgres pg_restore -d media-site -v file"
      - ""
      - "create the gemset:"
      - "   rvm ruby-2.6.5 do rvm gemset create media-site"
      - ""
      - "run capistrano:"
      - "   bundle exec cap app deploy"
      - "   bundle exec cap app elasticsearch:create_index"
      - "   bundle exec cap app elasticsearch:update"
      - ""
      - "optionally, modify profile of media user:"
      - "  .bashrc: cd media-site/shared"
      - "  .bash_profile: export RAILS_ENV=production"
