---
- name: Add SSH keys to rails user for cap deployment
  authorized_key:
    user: media
    manage_dir: true
    state: present
    key: "{{ lookup('keepass', 'ansible/authorized_keys/' + item.name + '.notes') }}"
  with_items:
    - "{{ users }}"
  when: item.state != 'absent' and item.name != 'voc'

- file: path=/srv/media/media-site/shared/config state=directory
        mode=0755 owner=media group=media
- file: path=/srv/media/media-site/shared/log state=directory
        mode=0755 owner=media group=media

- copy: src=app/{{ item }}
        dest=/srv/media/media-site/shared/{{ item }}
        mode=0640 owner=media group=media
  loop:
    - clear_caches.sh
    - console
    - dump-public-fixtures.sh
    - reload_puma
    - update_related
    - update_relive_config
    - update_streaming_config

- template: src=app/{{ item }}
            dest=/srv/media/media-site/shared/{{ item }}
            mode=0640 owner=media group=media
  loop:
    - update_promoted
    - update_view_counts

- template: src=app/{{ item }}
            dest=/srv/media/media-site/shared/config/{{ item }}
            mode=0640 owner=media group=media
  loop:
    - database.yml
    - secrets.yml
    - puma.rb

- copy: content={{ app_settings }}
        dest=/srv/media/media-site/shared/config/settings.yml
        owner=media group=media mode=0640

- copy: content={{ app_dotenv }}
        dest=/srv/media/media-site/shared/.env.production
        owner=media group=media mode=0640

- copy: content="ruby-{{ ruby_version }}@media-site"
        dest=/srv/media/media-site/shared/.ruby-version
        owner=media group=media mode=0640

- copy: src=logrotate
        dest=/etc/logrotate.d/local-media-site
        mode=0644 owner=root group=root

- template: src=voctoweb-puma.service
            dest=/etc/systemd/system/voctoweb-puma.service
            mode=0644 owner=root group=root

- template: src=voctoweb-sidekiq.service
            dest=/etc/systemd/system/voctoweb-sidekiq.service
            mode=0644 owner=root group=root

- systemd: state=started enabled=yes name=voctoweb-puma.service
- systemd: state=started enabled=yes name=voctoweb-sidekiq.service


- cron: user=media minute="20" cron_file="dump_public_fixtures"
        job="/srv/media/media-site/shared/dump-public-fixtures.sh"
- cron: user=media minute="40" cron_file="update_promoted"
        job="/srv/media/media-site/shared/update_promoted > /dev/null 2>&1"
- cron: user=media minute="*/15" cron_file="update_view_counts"
        job="/srv/media/media-site/shared/update_view_counts > /dev/null 2>&1"
- cron: user=media minute="*/5" cron_file="update_streaming_config"
        job="/srv/media/media-site/shared/update_streaming_config > /dev/null 2>&1"
- cron: user=media minute="*/9" cron_file="update_relive_config"
        job="/srv/media/media-site/shared/update_relive_config > /dev/null 2>&1"
