---
  - name: restart nginx
    service: name=nginx state=restarted
    when: nginx is defined and nginx == 'yes'

  - include: ../../../handlers/nginx.yml
  - include: ../../../handlers/systemd.yml
  - include: ../../../roles/letsencrypt/handlers/main.yml domain={{ ansible_fqdn }}
