---
  - name: make sure ruby is installed
    apt: name=ruby state=latest

  - name: install register_relay client
    template: dest=/usr/local/sbin/register_relay
              src=register_relay/client.rb
              mode=0750 owner=root group=root
    notify:
      - trigger register_relay

  - name: install init script
    template: dest=/etc/init.d/send_relay_report
              src=register_relay/init.sh
              mode=0755 owner=root group=root
    notify:
      - trigger register_relay

  - name: ensure relay register service is enabled
    service:
      name: send_relay_report
      enabled: yes
      state: started

  - name: install register bandwith measure client
    template: dest=/usr/local/sbin/register_bw_measure
              src=measure_bw/client.rb
              mode=0750 owner=root group=root
