---
  - name: create directories
    file: dest={{ item }} state=directory
          owner=root group=root
    with_items:
      - /opt/rtmp_ingest/scripts/

  - name: copying rtmp_ingest-scripts
    template: dest=/opt/rtmp_ingest/scripts/rtmp_ingest_{{ item }}.sh
              src=rtmp_ingest/rtmp_ingest.sh.j2
              owner=root group=root mode=0755
    with_items:
      - "{{ rtmp_ingest_streams }}"




  - name: create rtmp_ingest systemd-units
    template: src=systemd-units/rtmp_ingest.service.j2
              dest="/etc/systemd/system/rtmp_ingest_{{ item }}.service"
              mode=0644 owner=root group=root
    with_items:
      - "{{ rtmp_ingest_streams }}"

  - name: reload systemd daemon
    command: systemctl daemon-reload
    changed_when: false

  - name: enable rtmp_ingest systemd-units
    service: name=rtmp_ingest_{{ item }}.service
             enabled=yes
             state=restarted
    with_items:
      - "{{ rtmp_ingest_streams }}"
