---
  - name: install haproxy package
    apt: name=haproxy state=latest
    tags: install

  - name: setup certboot-hook to aggregate haproxy combined cert-files
    template: src=haproxy/certbot-renewal-hook.sh.j2
              dest=/etc/letsencrypt/renewal-hooks/post/20-haproxy-{{ item }}
              mode=0755 owner=root group=root
    with_items:
      - cdn.c3voc.de
      - streaming.media.ccc.de

  - name: run certboot-hook once to aggregate haproxy combined cert-files
    shell: /etc/letsencrypt/renewal-hooks/post/20-haproxy-{{ item }}
    with_items:
      - cdn.c3voc.de
      - streaming.media.ccc.de

  # configure haproxy
  - name: create haproxy chroot directory
    file: dest=/usr/share/haproxy state=directory
          mode=0750 owner=haproxy group=haproxy
    tags: install

  - name: copy usa ip list
    copy: src=usa_subnetworks.txt
          dest=/etc/haproxy/usa_subnetworks.txt
          mode=0755 owner=haproxy group=haproxy
    tags:
      - install
      - config

  - name: copy dtag ip list
    copy: src=dtag_subnetworks.txt
          dest=/etc/haproxy/dtag_subnetworks.txt
          mode=0755 owner=haproxy group=haproxy
    tags:
      - install
      - config

  - name: create haproxy config
    template: src=haproxy/haproxy.cfg.j2
              dest=/etc/haproxy/haproxy.cfg
              owner=root group=root mode=0640
              validate='haproxy -f %s -c'
    notify: reload haproxy
    tags:
      - install
      - config
      - haproxy_deploy

  - name: autostart haproxy
    service: name=haproxy state=started enabled=yes
    tags: install
