- name: find local server rules
  find:
    paths: /etc/logcheck/ignore.d.server
    patterns: 'local,local*'
  register: ignore_server

- name: download local server rules
  fetch:
    src: "{{ item.path }}"
    dest: "roles/logcheck/files/{{ inventory_hostname }}/server/{{ item.path | basename }}"
    flat: yes
  with_items: "{{ ignore_server.files }}"

- name: find local violations rules
  find:
    paths: /etc/logcheck/violations.ignore.d
    patterns: 'local,local*'
  register: ignore_violations

- name: download local violations rules
  fetch:
    src: "{{ item.path }}"
    dest: "roles/logcheck/files/{{ inventory_hostname }}/violations/{{ item.path | basename }}"
    flat: yes
  with_items: "{{ ignore_violations.files }}"
