---
  - name: restart icecast2
    service: name=icecast2 state=restarted

  - name: restart nginx
    service: name=nginx state=restarted
    when: nginx is defined and nginx == 'yes'

  - name: trigger register_relay
    service: name=register_relay state=restarted

  - name: reload php-fpm
    service: name=php5-fpm state=reloaded

  - name: restart icedist
    service: name=icedist state=restarted

  - include: ../../../handlers/nginx.yml
  - include: ../../../handlers/rc_local.yml
  - include: ../../../handlers/sysctl.yml
  - include: ../../../handlers/systemd.yml
  - include: ../../../roles/letsencrypt/handlers/main.yml domain={{ ansible_fqdn }}
