---
  # Install packages
  - name: uninstall nginx-rtmp package
    apt: name=nginx-rtmp state=absent
    tags: install

  - name: install nginx package
    apt: name=nginx state=latest
    tags: install

  - name: install libnginx-mod-rtmp package
    apt: name=libnginx-mod-rtmp state=latest
    tags: install
    when: (rtmp is defined and rtmp == 'yes')

  - name: uninstall libnginx-mod-rtmp package
    apt: name=libnginx-mod-rtmp state=absent
    tags: install
    when: not (rtmp is defined and rtmp == 'yes')

  # Configure
  - name: configure nginx
    template: dest=/etc/nginx/nginx.conf
              src=nginx.conf.j2
              mode=0640 owner=root group=root
    notify:
      - reload nginx
    tags:
      - config
      - install

  # Manage vhost
  - name: remove default vhost
    file: dest=/etc/nginx/sites-enabled/default state=absent
    notify: reload nginx

  # Enable service
  - name: start nginx
    service: name=nginx enabled=yes state=started
    when: nginx is defined and nginx == 'yes'

  - name: stop nginx-rtmp
    service: name=nginx-rtmp enabled=no state=stopped
    failed_when: false

  # - name: setup certbot-hook to reload nginx when the cert changes
  #   template: src=certbot-renewal-hook.sh.j2
  #             dest=/etc/letsencrypt/renewal-hooks/post/20-nginx
  #             mode=0755 owner=root group=root

  # - name: run certbot-hook once to reload nginx with possibly new cert changes
  #   shell: /etc/letsencrypt/renewal-hooks/post/20-nginx

  # Cron job to reload nginx after ocsp update
  # TODO: Is there a better solution available?
  - name: reload nginx every morning for ocsp updates
    cron: name="reload nginx for ocsp update" hour=5 minute=5
          job="systemctl reload nginx" user=root
    tags: install