---
  # RTMP vhost
  - name: remove old rtmp master vhost
    file: dest="{{ item }}"
          state=absent
    with_items:
      - /etc/nginx/sites-enabled/rtmp_master.conf
      - /etc/nginx/sites-available/rtmp_master.conf
    when: not (rtmp is defined and rtmp == 'yes')
    notify:
      - reload nginx
    tags:
      - config
      - install

  - name: create rtmp master config
    template: dest="/etc/nginx/conf.d/rtmp_master.conf"
              src="conf.d/rtmp.conf.j2"
              mode=0640 owner=root group=root
    when: rtmp is defined and rtmp == 'yes'
    notify:
      - reload nginx
    tags:
      - config
      - install