---
  - hosts: loadbalancers
    roles:
      - { role: common, tags: ['common'] }
      - { role: letsencrypt, vars: { 'domain': '{{ ansible_fqdn }}'}, tags: ['letsencrypt'] }
      - { role: letsencrypt, vars: { 'domain': 'cdn.c3voc.de'}, tags: ['letsencrypt'] }
      - { role: letsencrypt, vars: { 'domain': 'streaming.media.ccc.de'}, tags: ['letsencrypt'] }
      - { role: loadbalancer, tags: ['loadbalancer'] }
