---
  - hosts: cdn
    roles:
      - { role: 'media-common', tags: ['media-common'] }

      - role: 'ansible-acmetool'
        when: ssl == 1 and acmetool_setup == 1
        tags: ['ansible-acmetool', 'nginx']

      - role: 'media-cdn'
        when: cdn == 1
        tags: ['media-cdn']

      - role: golang
        when: cdn == 1

      - role: 'media-mirror'
        when: mirror == 1
        tags: ['media-mirror']

      - role: rvm1-ansible
        when: app == 1
        tags: ['media-app', 'ruby']
        rvm1_rubies: ["{{ ruby_version }}"]
        rvm1_user: 'media'
        rvm1_install_path: '/srv/media/.rvm'
        rvm1_install_flags: '--auto-dotfiles --user-install'

      - role: 'media-app'
        when: app == 1
        tags: ['media-app']

      - { role: 'logcheck', tags: ['logcheck'] }

    vars:
      go_version: 1.13
      ruby_version: ruby-2.6.1
      # run acmetool setup
      acmetool_setup: 0
      # remove all configuration/state first
      acmetool_cleanup: 'false'
      # will overwrite local files
      download_logcheck: 'false'
      # will remove local logcheck rules before upload
      remove_logcheck: 'false'

      acmetool_websrv: "nginx"
      redis_bind: 127.0.0.1
      users:
        - { name: 'derpeter', state: 'absent' }
        - { name: 'danimo', state: 'absent' }
        - { name: 'florolf', state: 'absent' }
        - { name: 'meise', state: 'absent' }
        - { name: 'mm', state: 'absent' }
        - { name: 'voc', state: 'present' }
      uploaders: "{{ lookup('keepass', 'ansible/media/uploaders.notes') | from_yaml }}"
      downloaders: test.yml

      media_mirror_rsync: 'TODO keepass plz'
      google_maps_api_key: 'TODO keepass plz'
