---
  - hosts: media-assets
    roles:
      - role: media-assets
        gather_facts: no
        tags: ['media-assets']

  - hosts: media-cdn
    roles:
      - role: media-common
        tags: ['media-common']

      - role: acmetool
        when: ssl == 1 and acmetool_setup == 1
        tags: ['acmetool-install', 'nginx']

      - role: golang
        tags: ['golang']

      - role: media-cdn
        tags: ['media-cdn']

      - role: logcheck
        tags: ['logcheck']

  - hosts: media-mirror
    roles:
      - role: media-common
        tags: ['media-common']

      - role: acmetool
        when: ssl == 1 and acmetool_setup == 1
        tags: ['acmetool-install', 'nginx']

      - role: media-mirror
        tags: ['media-mirror']

      - role: logcheck
        tags: ['logcheck']

  - hosts: media-app
    roles:
      - role: media-common
        tags: ['media-common']

      - role: acmetool
        when: ssl == 1 and acmetool_setup == 1
        tags: ['acmetool-install', 'nginx']

      - role: media-app
        tags: ['media-app']

      - role: rvm1-ansible
        tags: ['media-app', 'ruby']
        rvm1_rubies: ['ruby-{{ ruby_version }}']
        rvm1_user: 'media'
        rvm1_install_path: '/srv/media/.rvm'
        rvm1_install_flags: '--auto-dotfiles --user-install'
        rvm1_rvm_version: 'stable'
        rvm1_autolib_mode: 0

  - hosts: media-app-db
    roles:
      - role: media-common
        tags: ['media-common']

      - role: media-app-db
        tags: ['media-app-db']
