---
  - hosts: minions
    roles:
      - { role: common, tags: ['common'] }
      - { role: crs-worker, tags: ['crsworker'], when: crs_token is defined and crs_secret is defined }
      - { role: minion, tags: ['minion'] }
    vars:
     ssh_allow_voc_password_login: 'yes'
