---
  - hosts: relays
    roles:
      - { role: common, tags: ['common'] }
      - { role: letsencrypt, vars: { 'domain': '{{ ansible_fqdn }}'}, tags: ['letsencrypt'] }
      - { role: monitoring-client, tags: ['monitoring'] }
      - { role: relay, tags: ['relay'] }
