---
 - hosts: transcoders
   roles:
     - { role: common, tags: ['common'] }
     - { role: monitoring-client, tags: ['monitoring'] }
     - { role: transcoder, tags: ['transcoder'] }
   vars:
     ssh_allow_voc_password_login: 'yes'
