---
  - hosts: web.c3voc.de
    roles:
      - { role: common, tags: ['common'] }
      - { role: letsencrypt, vars: { 'domain': 'c3voc.de'}, tags: ['letsencrypt'] }
      - { role: letsencrypt, vars: { 'domain': '{{ ansible_fqdn }}'}, tags: ['letsencrypt'] }
