---
  - include: nginx.yml
  - include: php.yml

  - name: install tracker specific packages
    apt: name={{ item }} state=latest
    with_items:
      - libxdiff0
      - mgdiff
      - curl
      - libxslt1.1
      - libintl-perl
      - php-xdiff
      - autopostgresqlbackup

  - name: git checkout tracker repo
    git: repo=https://github.com/crs-tools/tracker
         dest=/srv/www/cccongress
    tags:
      - install
      - pull
      - checkout

  - name: create logrotate config
    copy: src=tracker dest=/etc/logrotate.d

  - name: create cronjobs for lets encrypt / dehydrated
    copy: src=dehydrated dest=/etc/cron.d

