---
  - name: install defaut packages
    apt:
      state: latest
      update_cache: yes
      name:
        - build-essential
        - etckeeper
        - ethtool
        - git
        - htop
        - iftop
        - lockfile-progs
        - nginx
        - pv
        - rsync
        - smartmontools
        - strace
        - tmux
        - unattended-upgrades
        - vim
        - vnstat
        - zip
        - zsh

  - name: remove not needed packages
    apt: name={{ item }} state=absent
    with_items:
      - rpcbind
      - snapd
