---
  - name: install defaut packages
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - build-essential
      - etckeeper
      - ethtool
      - git
      - htop
      - iftop
      - lockfile-progs
      - nginx
      - pv
      - rssh
      - rsync
      - smartmontools
      - strace
      - tmux
      - unattended-upgrades
      - vim
      - vnstat
      - zip
      - zsh

  - name: remove not needed packages
    apt: name={{ item }} state=absent
    with_items:
      - rpcbind
      - snapd
