---
- name: install defaut packages
  apt:
    state: latest
    update_cache: yes
    name:
      - apt-transport-https
      - aptitude
      - build-essential
      - curl
      - etckeeper
      - ethtool
      - git
      - htop
      - iftop
      - lockfile-progs
      - net-tools
      - pv
      - rsync
      - smartmontools
      - strace
      - tmux
      - unattended-upgrades
      - neovim
      - vnstat
      - zip
      - zsh

- name: remove not needed packages
  apt:
    state: absent
    name:
      - rpcbind
      - snapd
      - vim
