---
  - shell: command -v zsh
    register: zsh_bin
    changed_when: false

  - group: name=sudo state=present

  - name: remove user "{{ item.name }}"
    user: state=absent remove=yes
         name={{ item.name }}
    when: item.state == 'absent'
    with_items:
      - "{{ users }}"
      - "{{ additional_users }}"

  - name: create user "{{ item.name }}"
    user: state=present
          name="{{ item.name }}"
          groups="ssh,sudo,adm" append=yes
          shell={{ user_shell | default(zsh_bin.stdout) }}
    with_items:
      - "{{ users }}"
      - "{{ additional_users }}"
    when: not item.state == 'absent'

  # - name: add user's authorized_keys
  #   authorized_key: user="{{ item.name }}" manage_dir=true key="{{ lookup('keepass', 'ansible/authorized_keys/' + item.name + '.notes') }}"
  #                   state=present exclusive=yes
  #   with_items:
  #     - "{{ users }}"
  #     - "{{ additional_users }}"
  #   when: item.state != 'absent' and item.name != 'voc'

