---
  - include: general.yml
  - include: packages.yml
  - include: slim.yml
  - include: x11vnc.yml

  - include: undeploy-voctogui.yml
  - include: aes67-loudness.yml
    when: aes67_loudness is defined

  - include: rc.local.yml
    tags:
      - iptables
      - rclocal
