---
  # install general acr-notebook packages
  - name: install packages required to be a acr-notebook
    apt: name={{ item }} state=latest
    with_items:
      - runit
      - xserver-xorg
      - x11-xserver-utils
      - slim
      - x11vnc
      - xterm
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-alsa
      - gstreamer1.0-tools
      - libgstreamer1.0-0
      - ffmpeg
      - python3
      - gnome-themes-standard
      - lxde
      - chromium

  # uninstall general acr-notebook packages
  - name: uninstall packages not required to be a acr-notebook
    apt: name={{ item }} state=absent
    with_items:
      - xscreensaver
