---
  # systemctl
  - name: Probe for systemctl
    shell: "command -v systemctl"
    register: systemctl_bin
    changed_when: false
    ignore_errors: yes

  # sysctl
  - name: Probe for sysctl
    shell: "command -v sysctl"
    register: sysctl_bin
    changed_when: false
    ignore_errors: yes

  # ffmpeg
  - name: Probe for ffmpeg
    shell: "command -v ffmpeg"
    register: ffmpeg_bin
    changed_when: false
    ignore_errors: yes

  # timedatectl
  - name: Probe for timedatectl
    shell: "command -v timedatectl"
    register: timedatectl_bin
    changed_when: false
    ignore_errors: yes

  # libvirtd
  - name: Probe for libvirtd
    shell: "command -v libvirtd"
    register: libvirtd_bin
    changed_when: false
    ignore_errors: yes
